### ISSUE TITLE
Template render bug?  Maybe

### ISSUE THREAD

**Issue by findborg** [inca/voie-starter-webpack#4]
I think that I found a bug or,  I am just doing something small wrong.  I have found that if I do not wrap the code inside the `<template>` with a general div.  When I change a state,  that template will not be replaced.  But,  as long as I use the general div the states work as intended.
This is what I have to do to make it work:

```
<template>
<div>
    <h1>h1 Heading</h1>
    <h2>h2 Heading</h2>
    <h3>h3 Heading</h3>
    <h4>h4 Heading</h4>
    <h5>h5 Heading</h5>
    <h6>h6 Heading</h6>
</div>
</template>
```

**Comment by inca** [comment]
That's kinda known feature of Vue, see [Fragment instance](http://vuejs.org/guide/components.html#Fragment_Instance)

**Comment by inca** [comment]
So yep, all views should have a single top-level element. Perhaps worth mentioning in Voie docs as well.
